[package]
name = "assignment_6"
version = "0.1.0"
authors = ["Arifullah Khan <arifullah.khan@teo-intl.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
